Updates setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -6,6 +6,11 @@ set -o pipefail
 
 # If need be nginx can proxy to another ip eg for docker env, or virtual machine
 
+if [ ! -f .env ]; then
+    echo ".env file not found!"
+    exit 1
+fi
+
 set -a
 source .env
 set +a
@@ -74,7 +79,7 @@ EOF
 if ! [ -z ${APP_SUBDOMAINS+x} ];
 then
   IFS=, SUBDOMAINS=($APP_SUBDOMAINS)
-  for SUBDOMAIN in ${SUBDOMAINS[@]}; do
+  for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
 
     cat >> "/usr/local/etc/nginx/servers/${APP_SUBDOMAIN}.conf" <<-EOFSINGLE
 
@@ -105,18 +110,14 @@ server {
   }
 }
 EOFSINGLE
-
-
-
   done
 fi
 
 
-
 # Restarting nginx
 echo "Restarting nginx..."
-sudo launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
-sudo launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist && echo "nginx started."
+sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
+sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist && echo "nginx started."
 echo "-------------------------------------"
 echo "Your app has been added."
 echo "Your next steps..."
