Restore setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,38 +1,131 @@
-#!/usr/bin/env ruby
-require 'pathname'
-require 'fileutils'
-include FileUtils
+#!/usr/bin/env bash
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
+set -o nounset
+set -o errexit
+set -o pipefail
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+# If need be nginx can proxy to another ip eg for docker env, or virtual machine
 
-chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file.
+if [ ! -f .env ]; then
+    echo ".env file not found!"
+    exit 1
+fi
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+set -a
+source .env
+set +a
 
-  # Install JavaScript dependencies if using Yarn
-  # system('bin/yarn')
+# Bootstrap the site - sets up symlinks to database.yml, etc. Be sure to set the correct dropbox folder in bootstrap first.
+bin/bootstrap
+
+# Create config file for the app / site.
+cat > "/usr/local/etc/nginx/servers/${APP_SUBDOMAIN}.conf" <<-EOF
+server {
+    listen *:443;
+    server_name ${ASSETS_SUBDOMAIN}.atomicjolt.xyz;
+
+    ssl on;
+    ssl_session_cache         builtin:1000  shared:SSL:10m;
+    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
+    ssl_ciphers               HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
+    ssl_prefer_server_ciphers on;
+
+    ssl_certificate     ssl/STAR_atomicjolt_xyz.crt;
+    ssl_certificate_key ssl/STAR_atomicjolt_xyz.key;
+
+    location / {
+
+      proxy_set_header   Host \$host;
+      proxy_set_header   X-Forwarded-Ssl on;
+      proxy_set_header   X-Forwarded-For \$remote_addr;
+      proxy_set_header   X-Forwarded-Proto \$scheme;
+      proxy_set_header   X-Real-IP        \$remote_addr;
+      proxy_set_header   Upgrade \$http_upgrade;
+      proxy_set_header   Connection "upgrade";
+      proxy_http_version 1.1;
+
+      proxy_pass         http://127.0.0.1:${ASSETS_PORT}/;
+
+    }
+}
+
+server {
+
+    listen *:443;
+    server_name ${APP_SUBDOMAIN}.atomicjolt.xyz;
+
+    ssl on;
+    ssl_session_cache         builtin:1000  shared:SSL:10m;
+    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
+    ssl_ciphers               HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
+    ssl_prefer_server_ciphers on;
+
+    ssl_certificate     ssl/STAR_atomicjolt_xyz.crt;
+    ssl_certificate_key ssl/STAR_atomicjolt_xyz.key;
+
+    location / {
+
+      proxy_set_header   Host \$host;
+      proxy_set_header   X-Forwarded-Ssl on;
+      proxy_set_header   X-Forwarded-For \$remote_addr;
+      proxy_set_header   X-Forwarded-Proto \$scheme;
+      proxy_set_header   X-Real-IP        \$remote_addr;
+      proxy_http_version 1.1;
+      proxy_pass         http://127.0.0.1:${APP_PORT}/;
+
+    }
+}
+EOF
+
+#Add app subdomains
+if ! [ -z ${APP_SUBDOMAINS+x} ];
+then
+  IFS=, SUBDOMAINS=($APP_SUBDOMAINS)
+  for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
+
+    cat >> "/usr/local/etc/nginx/servers/${APP_SUBDOMAIN}.conf" <<-EOFSINGLE
+
+server {
+
+  listen *:443;
+  server_name ${SUBDOMAIN}.atomicjolt.xyz;
+
+  ssl on;
+  ssl_session_cache         builtin:1000  shared:SSL:10m;
+  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
+  ssl_ciphers               HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
+  ssl_prefer_server_ciphers on;
+
+  ssl_certificate     ssl/STAR_atomicjolt_xyz.crt;
+  ssl_certificate_key ssl/STAR_atomicjolt_xyz.key;
+
+  location / {
+    proxy_set_header   Host \$host;
+    proxy_set_header   X-Forwarded-Ssl on;
+    proxy_set_header   X-Forwarded-For \$remote_addr;
+    proxy_set_header   X-Forwarded-Proto \$scheme;
+    proxy_set_header   X-Real-IP        \$remote_addr;
+    proxy_set_header   Upgrade \$http_upgrade;
+    proxy_set_header   Connection "upgrade";
+    proxy_http_version 1.1;
+    proxy_pass         http://127.0.0.1:${APP_PORT}/;
+
+  }
+}
+EOFSINGLE
+  done
+fi
 
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   cp 'config/database.yml.sample', 'config/database.yml'
-  # end
-
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:setup'
-
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
-
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+# Restarting nginx
+echo "Restarting nginx..."
+sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
+sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist && echo "nginx started."
+echo "-------------------------------------"
+echo "Your app has been added."
+echo "Your next steps..."
+echo "rails s -p ${APP_PORT}"
+echo "yarn hot"
+echo "Visit your assets here: https://${ASSETS_SUBDOMAIN}.atomicjolt.xyz"
+echo "Visit your app / project here: https://${APP_SUBDOMAIN}.atomicjolt.xyz"
+echo "-------------------------------------"
